import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import React from 'react';
import { useState, useEffect } from 'react';
import axios from 'axios';
import divider from '../public/images/pattern-divider-desktop.svg';
import randombtn from '../public/images/icon-dice.svg';
const Home: NextPage = () => {
	const [data, setData] = useState({
		id: 666,
		advice: 'Loading...',
	});

	const getData = async () => {
		await axios.get('	https://api.adviceslip.com/advice').then((res) => {
			console.log('data >>>', res.data.slip);
			setData({
				id: res.data.slip.id,
				advice: res.data.slip.advice,
			});
			console.log(data);
		});
	};

	// getData();
	useEffect(() => {
		getData();
	}, []);

	return (
		<div className='flex justify-center content-center min-h-screen'>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
				<link
					rel='stylesheet'
					href='https://fonts.googleapis.com/css?family=Manrope'
				/>
			</Head>

			<main className='flex flex-col flex-wrap justify-center content-center min-h-full text-center'>
				<div className='main flex flex-col flex-wrap content-center rounded-3xl'>
					<p className='id mt-12 mb-6'>{`ADVICE #${data.id}`}</p>
					<h3 className='advice mb-10'>{`"${data.advice}"`}</h3>
					<Image
						src={divider}
						className='object-contain h-16 w-444 '></Image>
					<div
						className='circle rounded-full cursor-pointer flex items-center justify-center h-screen self-center mt-10'
						onClick={getData}>
						<Image
							src={randombtn}
							className='object-contain h-24 w-24 '></Image>
					</div>
				</div>
			</main>
		</div>
	);
};

export default Home;
